### PR TITLE
Pay Pal button round 2 because idk how to pull request

### PR DESCRIPTION
**Pull request by sthall04**
Do this one I guess if the if I didn't do the other pull request right

### CODE REVIEW

**Comment by pmgreg3** [comment]
I think we need something similar to the outcome described on this page: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/

**Comment by tbrownie98** [comment]
Pedro, your link doesn't work

**Comment by pmgreg3** [comment]
Okay, I updated the link.

**Comment by tbrownie98** [comment]
I closed the other pull request because this one is better. We would need their PayPal information to do that, Pedro.

**Comment by pmgreg3** [comment]
I was under the impression we'd create a dummy account for them to fill

**Comment by pmgreg3** [comment]
The code is fine if thats the case.  we can merge

**Comment by tbrownie98** [comment]
That's fine by me. Can we add it to hotfixes?

**Comment by pmgreg3** [comment]
yea i can add that in there

**Comment by tbrownie98** [comment]
Just did

**Pull request merged**
